import type { Product } from "./types";

export const products = [
  {
    slug: "trafego-pago-do-zero-a-escala",
    title: "Tráfego Pago: do Zero à Escala",
    subtitle: "O guia prático para criar campanhas com método, interpretar métricas e transformar investimento em crescimento previsível.",
    description: "Um método prático e visual para criar, otimizar e escalar campanhas em Meta Ads, Google Ads e TikTok Ads com clareza, dados e uma sequência de execução.",
    shortDescription: "Crie, analise e evolua campanhas com um método claro para as principais plataformas de anúncios.",
    price: 47,
    currency: "BRL",
    coverImage: "/ebook-trafego.png.png",
    gallery: ["/ebook-trafego.png.png"],
    category: "marketing",
    author: "EscalaHub",
    benefits: [
      { title: "Decisões com método", description: "Uma linha de raciocínio clara para planejar, analisar e agir sem depender de achismos." },
      { title: "Métricas sem confusão", description: "Explicações diretas para entender os indicadores que realmente orientam uma campanha." },
      { title: "Aplicação prática", description: "Conteúdo organizado para consultar durante a criação e a otimização dos seus anúncios." },
    ],
    learning: [
      { title: "Planejar com clareza", description: "Defina objetivos, orçamento e estrutura antes de colocar qualquer campanha no ar." },
      { title: "Encontrar o público certo", description: "Crie segmentações relevantes e entenda como alcançar pessoas com intenção real." },
      { title: "Dominar as métricas", description: "Interprete CPM, CTR, CPC, CPA e ROAS sem se perder em relatórios complexos." },
      { title: "Otimizar e escalar", description: "Identifique vencedores, reduza desperdícios e cresça mantendo a operação saudável." },
    ],
    modules: [
      { title: "Fundamentos", description: "Como o tráfego pago funciona e o que precisa estar pronto antes do primeiro anúncio.", topics: ["Objetivos", "Oferta", "Jornada"] },
      { title: "Estrutura", description: "Campanhas, conjuntos, anúncios e uma organização que facilita a leitura dos resultados.", topics: ["Campanhas", "Conjuntos", "Anúncios"] },
      { title: "Públicos", description: "Segmentação, intenção e estratégias para diferentes momentos da jornada de compra.", topics: ["Interesses", "Remarketing", "Intenção"] },
      { title: "Criativos", description: "Princípios de mensagem, oferta e formato para anúncios que conquistam atenção.", topics: ["Mensagem", "Formatos", "Testes"] },
      { title: "Métricas", description: "Os indicadores essenciais e uma sequência clara para diagnosticar problemas.", topics: ["CTR", "CPC", "CPA", "ROAS"] },
      { title: "Escala", description: "Critérios para aumentar investimento, testar variações e proteger a rentabilidade.", topics: ["Otimização", "Orçamento", "Controle"] },
    ],
    audience: [
      { title: "Iniciantes", description: "Para quem quer começar com uma base organizada e evitar atalhos confusos." },
      { title: "Gestores de tráfego", description: "Para quem busca um processo mais claro de análise, otimização e escala." },
      { title: "Empreendedores", description: "Para quem precisa entender melhor como o investimento em mídia gera resultado." },
      { title: "Freelancers", description: "Para profissionais que desejam estruturar campanhas com mais segurança." },
      { title: "Pequenos negócios", description: "Para operações que precisam aproveitar melhor cada real investido em anúncios." },
    ],
    faq: [
      { question: "Preciso ter experiência com anúncios?", answer: "Não. O conteúdo começa pelos fundamentos e avança em uma sequência lógica, adequada para quem está começando ou quer reorganizar conhecimentos." },
      { question: "Como recebo o e-book?", answer: "Após a confirmação do pagamento, o acesso ao material digital é liberado para você iniciar a leitura." },
      { question: "O pagamento é único?", answer: "Sim. O valor é cobrado uma única vez, sem mensalidade ou assinatura." },
      { question: "Por quanto tempo terei acesso?", answer: "O acesso ao material é permanente, para que você possa consultar o guia sempre que precisar." },
      { question: "O conteúdo serve para quais plataformas?", answer: "Os princípios apresentados ajudam a estruturar campanhas em plataformas como Meta Ads, Google Ads e TikTok Ads." },
      { question: "Como funciona a garantia?", answer: "Você tem 7 dias para acessar e avaliar o material. Dentro desse prazo, pode solicitar o reembolso caso entenda que o produto não atende às suas necessidades." },
    ],
    testimonials: [],
    checkoutUrl: "/checkout?product=trafego-pago-do-zero-a-escala",
    featured: true,
    badge: "Produto em destaque",
    status: "published",
    seo: {
      title: "Tráfego Pago do Zero à Escala | E-book Prático",
      description: "E-book digital para aprender a criar, analisar e escalar campanhas em Meta Ads, Google Ads e TikTok Ads com um método claro.",
      keywords: ["tráfego pago", "e-book tráfego pago", "Meta Ads", "Google Ads", "TikTok Ads", "métricas de marketing", "escala de campanhas"],
      openGraphImage: "/opengraph-image",
      twitterImage: "/twitter-image",
    },
    format: "E-book digital",
    accessLabel: "Permanente",
    guaranteeDays: 7,
    platforms: ["Meta Ads", "Google Ads", "TikTok Ads"],
    delivery: {
      sourceUrlEnvironmentVariable: "PRODUCT_TRAFEGO_DOWNLOAD_URL",
      sourceAuthorizationEnvironmentVariable: "PRODUCT_TRAFEGO_DOWNLOAD_AUTHORIZATION",
      fileName: "trafego-pago-do-zero-a-escala.pdf",
      contentType: "application/pdf",
    },
  },
] as const satisfies readonly Product[];
