import { FiSearch, FiUsers } from "react-icons/fi";
import { AdminPageHeader, DataPanel, EmptyState, Pagination } from "@/components/admin/AdminUI";
import { Button } from "@/components/ui/Button";
import { formatDateTime } from "@/lib/admin/format";
import { getAdminStore } from "@/lib/admin/store";
import { getProductBySlug } from "@/lib/catalog";

export default async function AdminCustomersPage({ searchParams }: { searchParams: Promise<{ q?: string; page?: string }> }) {
  const params = await searchParams;
  const page = Math.max(1, Number.parseInt(params.page ?? "1", 10) || 1);
  const result = await getAdminStore().listCustomers(params.q ?? "", page, 20);
  return <><AdminPageHeader eyebrow="Relacionamento" title="Clientes" description={`${result.total} clientes identificados a partir dos pedidos, acessos e downloads.`} /><DataPanel className="mb-5 p-4"><form method="get" className="flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><FiSearch className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-500" aria-hidden="true" /><input name="q" defaultValue={params.q} className="input-control pl-11" placeholder="Pesquisar nome, e-mail ou produto" aria-label="Pesquisar clientes" /></label><Button type="submit"><FiSearch />Pesquisar</Button></form></DataPanel><DataPanel>{result.items.length ? <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b border-white/[.08] text-[10px] uppercase tracking-[.12em] text-zinc-500"><tr><th className="px-5 py-4">Cliente</th><th className="px-4 py-4">Produtos</th><th className="px-4 py-4">Pedidos</th><th className="px-4 py-4">Status</th><th className="px-4 py-4">Último login</th><th className="px-5 py-4">Downloads</th></tr></thead><tbody className="divide-y divide-white/[.065]">{result.items.map((customer) => <tr key={customer.email} className="hover:bg-white/[.02]"><td className="px-5 py-4"><span className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-blue-400/10 text-blue-200"><FiUsers /></span><span><strong className="block text-white">{customer.name || "Cliente"}</strong><span className="mt-1 block text-xs text-zinc-500">{customer.email}</span></span></span></td><td className="max-w-72 px-4 py-4 text-zinc-300">{customer.products.map((slug) => getProductBySlug(slug)?.title ?? slug).join(", ")}</td><td className="px-4 py-4 text-zinc-300">{customer.approvedOrders}/{customer.totalOrders} aprovados</td><td className="px-4 py-4"><span className={customer.approvedOrders ? "text-emerald-300" : "text-amber-300"}>{customer.approvedOrders ? "Cliente" : "Sem aprovação"}</span></td><td className="px-4 py-4 text-xs text-zinc-500">{formatDateTime(customer.lastLoginAt)}</td><td className="px-5 py-4 font-bold text-white">{customer.downloads}</td></tr>)}</tbody></table></div> : <EmptyState title="Nenhum cliente encontrado" />}<Pagination pathname="/admin/clientes" page={page} totalPages={result.totalPages} params={{ q: params.q }} /></DataPanel></>;
}
