import { FiCheckCircle, FiClock, FiCode, FiSearch, FiZap } from "react-icons/fi";
import { AdminPageHeader, DataPanel, EmptyState, Pagination } from "@/components/admin/AdminUI";
import { Button } from "@/components/ui/Button";
import { formatDateTime } from "@/lib/admin/format";
import { getAdminStore } from "@/lib/admin/store";

export default async function AdminWebhooksPage({ searchParams }: { searchParams: Promise<{ q?: string; page?: string }> }) {
  const params = await searchParams;
  const page = Math.max(1, Number.parseInt(params.page ?? "1", 10) || 1);
  const result = await getAdminStore().listWebhooks(params.q ?? "", page, 20);
  return <><AdminPageHeader eyebrow="Gateway" title="Eventos Stripe" description={`${result.total} eventos recebidos. O payload exibido é sanitizado e não contém cartões, tokens ou segredos.`} /><DataPanel className="mb-5 p-4"><form method="get" className="flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><FiSearch className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-500" /><input name="q" defaultValue={params.q} className="input-control pl-11" placeholder="Evento, pedido, sessão ou resultado" aria-label="Pesquisar webhooks" /></label><Button type="submit"><FiSearch />Pesquisar</Button></form></DataPanel><DataPanel>{result.items.length ? <div className="divide-y divide-white/[.07]">{result.items.map((event) => <details key={event.id} className="group px-5 py-4"><summary className="grid cursor-pointer list-none gap-3 sm:grid-cols-[minmax(0,1fr)_180px_100px_120px] sm:items-center"><span className="flex min-w-0 items-center gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-violet-400/10 text-violet-200"><FiZap /></span><span className="min-w-0"><strong className="block truncate text-sm text-white">{event.eventType || "Evento legado"}</strong><span className="mt-1 block truncate font-mono text-[11px] text-zinc-500">{event.eventId || event.id}</span></span></span><span className="font-mono text-xs text-zinc-400">{event.orderId.slice(0, 8)}…</span><span className={event.processedAt ? "text-emerald-300" : "text-amber-300"}>{event.processedAt ? <span className="flex items-center gap-2 text-xs"><FiCheckCircle />Processado</span> : <span className="flex items-center gap-2 text-xs"><FiClock />Recebido</span>}</span><span className="text-xs text-zinc-500">{event.latencyMs === null ? "—" : `${event.latencyMs} ms`}</span></summary><div className="mt-4 grid gap-4 rounded-xl border border-white/[.07] bg-black/20 p-4 lg:grid-cols-[220px_minmax(0,1fr)]"><dl className="space-y-3 text-xs"><div><dt className="caption-label">Recebido</dt><dd className="mt-1 text-zinc-300">{formatDateTime(event.receivedAt)}</dd></div><div><dt className="caption-label">Resultado</dt><dd className="mt-1 text-zinc-300">{event.result}</dd></div><div><dt className="caption-label">Checkout Session</dt><dd className="mt-1 break-all font-mono text-zinc-400">{event.gatewayPaymentId}</dd></div></dl><div><p className="mb-2 flex items-center gap-2 text-xs font-bold text-zinc-300"><FiCode />JSON sanitizado</p><pre className="max-h-72 overflow-auto rounded-xl bg-black/25 p-4 text-xs leading-5 text-zinc-300">{JSON.stringify(event.payload, null, 2)}</pre></div></div></details>)}</div> : <EmptyState title="Nenhum webhook encontrado" />}<Pagination pathname="/admin/webhooks" page={page} totalPages={result.totalPages} params={{ q: params.q }} /></DataPanel></>;
}
